

Running executable

[ballerina/http] started HTTP/WS listener 172.27.192.184:42121
Scheduled watcher for step 24 with interval 2.0. JobId: {"id":704691}
[ballerina/http] started HTTP/WS listener 0.0.0.0:9090
error GenericClientError ("Something wrong with the connection",error("Connection refused: localhost/127.0.0.1:5005"))
error GenericClientError ("Something wrong with the connection",error("Connection refused: localhost/127.0.0.1:5005"))
error GenericClientError ("Something wrong with the connection",error("Connection refused: localhost/127.0.0.1:5005"))
error GenericClientError ("Something wrong with the connection",error("Connection refused: localhost/127.0.0.1:5005"))
error GenericClientError ("Something wrong with the connection",error("Connection refused: localhost/127.0.0.1:5005"))
error GenericClientError ("Something wrong with the connection",error("Connection refused: localhost/127.0.0.1:5005"))
Unscheduling watcher for step 24 because of repeated errors.
Unscheduled watcher for step 24. JobId: {"id":704691}
error GenericClientError ("Something wrong with the connection",error("Connection refused: localhost/127.0.0.1:5005"))
error: Connection between remote client and host is closed
error: Connection between remote client and host is closed
error: Connection between remote client and host is closed
error: Connection between remote client and host is closed
[2022-05-01 11:41:13,049] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.internal.scheduling.Scheduler.scheduleLocal(Scheduler.java:156)
        at io.ballerina.runtime.internal.scheduling.Scheduler.scheduleLocal(Scheduler.java:147)
        at ballerinai.transaction.0.commons.cleanupTransactions(commons.bal:52)
        at ballerinai.transaction.0.$value$Cleanup.execute(commons.bal:47)
        at ballerinai.transaction.0.$value$Cleanup.call(commons.bal)
        at io.ballerina.runtime.api.Runtime.lambda$invokeMethodAsync$2(Runtime.java:157)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:834)
 
[2022-05-01 11:41:13,054] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.values.BError.<init>(BError.java:37)
        at io.ballerina.runtime.internal.values.ErrorValue.<init>(ErrorValue.java:92)
        at io.ballerina.runtime.internal.values.ErrorValue.<init>(ErrorValue.java:82)
        at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:51)
        at io.ballerina.runtime.api.creators.ErrorCreator.createError(ErrorCreator.java:140)
        at io.ballerina.runtime.internal.scheduling.Scheduler.postProcess(Scheduler.java:383)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:339)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:834)
 
^C[ballerina/http] stopped HTTP/WS listener 0.0.0.0:9090
